// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-XaKExTgOrBVFHQ4paOUQmTtiRLlgjnU',
    appId: '1:109820847091:web:125882894ebbdee265a886',
    messagingSenderId: '109820847091',
    projectId: 'aft-firebase-app-1760071390',
    authDomain: 'aft-firebase-app-1760071390.firebaseapp.com',
    storageBucket: 'aft-firebase-app-1760071390.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CzPojuDi5_5eEkzNHANg89S7oQgi3Ew',
    appId: '1:109820847091:android:e992649ee0b026bc65a886',
    messagingSenderId: '109820847091',
    projectId: 'aft-firebase-app-1760071390',
    storageBucket: 'aft-firebase-app-1760071390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7IYCyExhiNpMYReqU-qLwidj-90q5-Iw',
    appId: '1:109820847091:ios:e3f686da70448e6765a886',
    messagingSenderId: '109820847091',
    projectId: 'aft-firebase-app-1760071390',
    storageBucket: 'aft-firebase-app-1760071390.firebasestorage.app',
    iosBundleId: 'com.lamontenunn.aftApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7IYCyExhiNpMYReqU-qLwidj-90q5-Iw',
    appId: '1:109820847091:ios:f079a741dda0bc9665a886',
    messagingSenderId: '109820847091',
    projectId: 'aft-firebase-app-1760071390',
    storageBucket: 'aft-firebase-app-1760071390.firebasestorage.app',
    iosBundleId: 'com.example.aftFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-XaKExTgOrBVFHQ4paOUQmTtiRLlgjnU',
    appId: '1:109820847091:web:b5291917741a6d7465a886',
    messagingSenderId: '109820847091',
    projectId: 'aft-firebase-app-1760071390',
    authDomain: 'aft-firebase-app-1760071390.firebaseapp.com',
    storageBucket: 'aft-firebase-app-1760071390.firebasestorage.app',
  );

}